server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://localhost:3306/froggyblog?createDatabaseIfNotExist=true&serverTimezone=Asia/Ho_Chi_Minh&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:

  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
      show-sql: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 247004369428-vqr04dl1423u0lg6mmuna5ph85628c2t.apps.googleusercontent.com
            clientSecret: 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
            scope:
                - email
                - profile
  messages:
    basename: message

jwt:
   secretKey: geG-4w9NviA-h6kt2DASBZf0o8bRqp0VJd9PZuZg78s.bwUF7PMAWODIxqqyqErNfn1ZWmKtTqLcQDb7GVTueTg.hmvUpKfPFuy8C2YbSvkTCOSHUl693Kjl7W95rrdu9do
   refreshKey: ZZ9cgC0Uh0fPyqv4fvEedXeaX7L378G2kvDH9l0-u00.6Szw_Yhs_kho1esPtah_68F8fVM0Nk1Bw7ZMtEwAWD8.kLpZGI7w5VxX5LBx-V4NeIH5J1vu461yNbcRA6vhzHE
   expiredTimeAccess: 900000
   expiredTimeRefresh: 2592000000
   audience: FroggyBlogReact
   issuer : FroggyBlogSpringBoot
mail:
    port: 587
    host: smtp.gmail.com
    username: antaodi321@gmail.com
    password: dxvcwkttgftasmuk
forgotPassword:
    required: confirm-required

avatar:
  path: https://ui-avatars.com/api/?color=fff&background=random&name=
